# Generated by Django 3.1.1 on 2020-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cutisey', '0002_auto_20201024_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
